# Generated by Django 5.2.17 on 2026-10-01 07:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_bill', models.CharField(default='Electricity Bill', max_length=250)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_structure_description', models.TextField(verbose_name='description')),
                ('fees_structure', models.FileField(upload_to='fees_structure/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Upload a PDF. Convert other documents to PDF first.')], verbose_name='PDF')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACADEMICS', 'Academics'), ('COCURRICULAR', 'Co-curricular'), ('ICT', 'ICT')], max_length=20)),
                ('picture', models.ImageField(upload_to='landing_page_pictures/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='news_images/')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_uploaded', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=255, unique=True, verbose_name='ID number')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('curriculum_vitae', models.FileField(blank=True, upload_to='curriculum_vitae/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Upload a PDF. Convert other documents to PDF first.')])),
                ('employment_duration', models.CharField(blank=True, max_length=200)),
                ('employment_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'non-teaching staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(choices=[('kenyan', 'Kenyan'), ('others', 'Other')], max_length=100)),
                ('student_admission_number', models.CharField(max_length=20, unique=True)),
                ('grade_level', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9')], max_length=10)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('clubs_organizations', models.TextField(blank=True)),
                ('sports_participation', models.TextField(blank=True)),
                ('awards', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(choices=[('parent or guardian', 'Parent or guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('cousin', 'Cousin'), ('trusted family friend', 'Trusted family friend')], max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('parent_guardian_name', models.CharField(max_length=255)),
                ('parent_guardian_phone', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_admission_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.CharField(max_length=200, unique=True, verbose_name='TSC number')),
                ('id_number', models.CharField(max_length=255, unique=True, verbose_name='ID number')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('curriculum_vitae', models.FileField(upload_to='curriculum_vitae/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Upload a PDF. Convert other documents to PDF first.')])),
                ('position', models.TextField()),
                ('awards', models.TextField(blank=True)),
                ('professional_organizations', models.CharField(max_length=200)),
                ('employment_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'teaching staff',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_fees_payable', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='ID, admission or TSC number')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnyOtherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_payments', to='schoolsystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(choices=[('TERM 1', 'Term 1'), ('TERM 2', 'Term 2'), ('TERM 3', 'Term 3')], max_length=10)),
                ('student_grade_level', models.CharField(blank=True, choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9')], max_length=10)),
                ('examination', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('BRAILLE LITERACY', 'Braille Literacy Activities'), ('BUSINESS STUDIES', 'Business Studies'), ('COMPUTER SCIENCE', 'Computer Science'), ('CREATIVE ARTS', 'Creative Arts'), ('ENGLISH LANGUAGE ACTIVITIES', 'English Language Activities'), ('ENVIRONMENTAL ACTIVITIES', 'Environmental Activities'), ('FOREIGN LANGUAGES', 'Foreign Languages (German, French, Mandarin, or Arabic)'), ('HEALTH EDUCATION', 'Health Education'), ('HOME SCIENCE', 'Home Science'), ('HYGIENE AND NUTRITION ACTIVITIES', 'Hygiene and Nutrition Activities'), ('INDIGENOUS LANGUAGES', 'Indigenous Languages'), ('INTEGRATED SCIENCE', 'Integrated Science'), ('KENYA SIGN LANGUAGE', 'Kenya Sign Language'), ('KISWAHILI LANGUAGE ACTIVITIES', 'Kiswahili Language Activities'), ('LIFE SKILLS', 'Life Skills'), ('MATHEMATICAL ACTIVITIES', 'Mathematical Activities'), ('MATHEMATICS', 'Mathematics'), ('MOVEMENT AND CREATIVE ACTIVITIES', 'Movement and Creative Activities'), ('PERFORMING ARTS', 'Performing Arts'), ('PHYSICAL AND HEALTH EDUCATION', 'Physical and Health Education'), ('PRE-BRAILLE ACTIVITIES', 'Pre-Braille Activities'), ('PRE-TECHNICAL AND PRE-CAREER EDUCATION', 'Pre-Technical and Pre-Career Education'), ('RELIGIOUS EDUCATION ACTIVITIES', 'Religious Education Activities'), ('RELIGIOUS EDUCATION CRE', 'Religious Education (CRE)'), ('RELIGIOUS EDUCATION IRE', 'Religious Education (IRE)'), ('RELIGIOUS EDUCATION HRE', 'Religious Education (HRE)'), ('SCIENCE AND TECHNOLOGY', 'Science and Technology'), ('SOCIAL STUDIES', 'Social Studies'), ('SPORTS AND PHYSICAL EDUCATION', 'Sports and Physical Education'), ('VISUAL ARTS', 'Visual Arts')], max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_comments', models.CharField(blank=True, max_length=255)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='schoolsystem.student')),
            ],
            options={
                'ordering': ['-year', '-term', 'examination'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='schoolsystem.subject'),
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Past Examinations', 'Past examinations'), ('ebooks', 'E-books and study guides'), ('Educational pictures', 'Educational pictures'), ('Educational Videos', 'Educational videos'), ('Educational links', 'Educational links'), ('General Resources', 'General resources')], max_length=20)),
                ('appropriate_grade', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9'), ('All students', 'All students')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='EducationalResources/')),
                ('link', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='schoolsystem.subject')),
            ],
            options={
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank deposit', 'Bank deposit'), ('Bank Transfer', 'Bank transfer'), ('M-pesa Payment', 'M-Pesa')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='schoolsystem.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='schoolsystem.term')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffGovernmentDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('TS', 'Teaching staff'), ('NTS', 'Non-teaching staff')], max_length=3)),
                ('deducted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_deduction', models.CharField(default='NHIF', max_length=100)),
                ('date_deducted', models.DateField(auto_now_add=True)),
                ('non_teaching_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schoolsystem.nonteachingstaff')),
                ('teaching_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schoolsystem.teachingstaff')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('non_teaching_staff', None), ('staff_type', 'TS'), ('teaching_staff__isnull', False)), models.Q(('non_teaching_staff__isnull', False), ('staff_type', 'NTS'), ('teaching_staff', None)), _connector='OR'), name='deduction_names_exactly_one_staff_member_of_its_type')],
            },
        ),
    ]
